# -----------------------------------
# -------- OPENOCD SERVER -----------
# -----------------------------------
FROM ubuntu:20.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    openocd \
 && rm -rf /var/lib/apt/lists/*

# Expose port
EXPOSE 3333 4444/tcp

ENTRYPOINT [ "openocd" ]
