version: "2.4"
services:
  # OpenOCD server
  openocd:
    build:
        context: .
        dockerfile: Dockerfile_openocd
    image: redox-fw-openocd:latest
    network_mode: host
    volumes:
      - ./:/nRF5_SDK/redox-w-firmware
    privileged: true
    command: -f /nRF5_SDK/redox-w-firmware/nrf-stlink.cfg
  # Nordic SDK toolchain
  toolchain:
    build:
        context: .
        dockerfile: Dockerfile_toolchain
    image: redox-fw-toolchain:latest
    network_mode: host
    command: sleep inf
    volumes:
      - ./:/nRF5_SDK/redox-w-firmware
    depends_on:
        - openocd
